// Auto-generated MojoJS binding
// Source: chromium_src/ash/webui/settings/public/constants/routes.mojom
// Module: chromeos.settings.mojom

'use strict';

// Module namespace
var chromeos = chromeos || {};
chromeos.settings = chromeos.settings || {};
chromeos.settings.mojom = chromeos.settings.mojom || {};


// Enum: Section
chromeos.settings.mojom.Section = {
  kNetwork: 0,
  kBluetooth: 1,
  kMultiDevice: 2,
  kPeople: 3,
  kDevice: 4,
  kPersonalization: 5,
  kApps: 6,
  kPrivacyAndSecurity: 7,
  kAccessibility: 8,
  kAboutChromeOs: 9,
  kKerberos: 10,
  kSystemPreferences: 11,
};

// Enum: Subpage
chromeos.settings.mojom.Subpage = {
  kEthernetDetails: 0,
  kWifiNetworks: 1,
  kWifiDetails: 2,
  kKnownNetworks: 3,
  kMobileDataNetworks: 4,
  kCellularDetails: 5,
  kTetherDetails: 6,
  kVpnDetails: 7,
  kApn: 8,
  kHotspotDetails: 9,
  kPasspointDetails: 10,
  kBluetoothDevices: 11,
  kBluetoothDeviceDetail: 12,
  kBluetoothSavedDevices: 13,
  kMultiDeviceFeatures: 14,
  kNearbyShare: 15,
  kSyncControls: 16,
  kSyncSetup: 17,
  kSyncDeprecatedAdvanced: 18,
  kPointers: 19,
  kKeyboard: 20,
  kStylus: 21,
  kDisplay: 22,
  kStorage: 23,
  kExternalStorage: 24,
  kPower: 25,
  kAudio: 26,
  kPerDeviceKeyboard: 27,
  kPerDeviceMouse: 28,
  kPerDeviceTouchpad: 29,
  kPerDevicePointingStick: 30,
  kPerDeviceKeyboardRemapKeys: 31,
  kGraphicsTablet: 32,
  kCustomizeMouseButtons: 33,
  kCustomizeTabletButtons: 34,
  kCustomizePenButtons: 35,
  kSearch: 36,
  kAppManagement: 37,
  kAppDetails: 38,
  kGooglePlayStore: 39,
  kPluginVmSharedPaths: 40,
  kPluginVmUsbPreferences: 41,
  kAppNotifications: 42,
  kArcVmUsbPreferences: 43,
  kManageIsolatedWebApps: 44,
  kAppNotificationsManager: 45,
  kAppParentalControls: 46,
  kCrostiniDetails: 47,
  kCrostiniManageSharedFolders: 48,
  kCrostiniUsbPreferences: 49,
  kCrostiniBackupAndRestore: 50,
  kCrostiniPortForwarding: 51,
  kCrostiniExtraContainers: 52,
  kBruschettaDetails: 53,
  kBruschettaUsbPreferences: 54,
  kBruschettaManageSharedFolders: 55,
  kTimeZone: 56,
  kManageOtherPeopleV2: 57,
  kSecurityAndSignInV2: 58,
  kFingerprintV2: 59,
  kSmartPrivacy: 60,
  kPrivacyHub: 61,
  kPrivacyHubMicrophone: 62,
  kPrivacyHubCamera: 63,
  kPrivacyHubGeolocation: 64,
  kPrivacyHubGeolocationAdvanced: 65,
  kInputMethodOptions: 66,
  kLanguages: 67,
  kInput: 68,
  kEditDictionary: 69,
  kJapaneseManageUserDictionary: 70,
  kAppLanguages: 71,
  kNetworkFileShares: 72,
  kOfficeFiles: 73,
  kGoogleDrive: 74,
  kOneDrive: 75,
  kPrintingDetails: 76,
  kManageAccessibility: 77,
  kTextToSpeech: 78,
  kSwitchAccessOptions: 79,
  kTextToSpeechPage: 80,
  kDisplayAndMagnification: 81,
  kKeyboardAndTextInput: 82,
  kCursorAndTouchpad: 83,
  kAudioAndCaptions: 84,
  kSelectToSpeak: 85,
  kChromeVox: 86,
  kFaceGazeSettings: 87,
  kMouseKeysSettings: 88,
  kDetailedBuildInfo: 89,
  kInternalStorybook: 90,
  kKerberosAccountsV2: 91,
};
