// Auto-generated MojoJS binding
// Source: chromium_src/media/capture/video/chromeos/mojom/camera_metadata_tags.mojom
// Module: cros.mojom

'use strict';

// Module namespace
var cros = cros || {};
cros.mojom = cros.mojom || {};


// Enum: CameraMetadataSection
cros.mojom.CameraMetadataSection = {
  ANDROID_COLOR_CORRECTION: 0,
  ANDROID_CONTROL: 1,
  ANDROID_DEMOSAIC: 2,
  ANDROID_EDGE: 3,
  ANDROID_FLASH: 4,
  ANDROID_FLASH_INFO: 5,
  ANDROID_HOT_PIXEL: 6,
  ANDROID_JPEG: 7,
  ANDROID_LENS: 8,
  ANDROID_LENS_INFO: 9,
  ANDROID_NOISE_REDUCTION: 10,
  ANDROID_QUIRKS: 11,
  ANDROID_REQUEST: 12,
  ANDROID_SCALER: 13,
  ANDROID_SENSOR: 14,
  ANDROID_SENSOR_INFO: 15,
  ANDROID_SHADING: 16,
  ANDROID_STATISTICS: 17,
  ANDROID_STATISTICS_INFO: 18,
  ANDROID_TONEMAP: 19,
  ANDROID_LED: 20,
  ANDROID_INFO: 21,
  ANDROID_BLACK_LEVEL: 22,
  ANDROID_SYNC: 23,
  ANDROID_REPROCESS: 24,
  ANDROID_DEPTH: 25,
  ANDROID_LOGICAL_MULTI_CAMERA: 26,
  ANDROID_DISTORTION_CORRECTION: 27,
  ANDROID_HEIC: 28,
  ANDROID_HEIC_INFO: 29,
  ANDROID_AUTOMOTIVE: 30,
  ANDROID_AUTOMOTIVE_LENS: 31,
  ANDROID_SECTION_COUNT: 32,
  VENDOR_SECTION: 33,
};
cros.mojom.CameraMetadataSectionSpec = { $: mojo.internal.Enum() };

// Enum: CameraMetadataSectionStart
cros.mojom.CameraMetadataSectionStart = {
  ANDROID_COLOR_CORRECTION_START: 0,
  ANDROID_CONTROL_START: 1,
  ANDROID_DEMOSAIC_START: 2,
  ANDROID_EDGE_START: 3,
  ANDROID_FLASH_START: 4,
  ANDROID_FLASH_INFO_START: 5,
  ANDROID_HOT_PIXEL_START: 6,
  ANDROID_JPEG_START: 7,
  ANDROID_LENS_START: 8,
  ANDROID_LENS_INFO_START: 9,
  ANDROID_NOISE_REDUCTION_START: 10,
  ANDROID_QUIRKS_START: 11,
  ANDROID_REQUEST_START: 12,
  ANDROID_SCALER_START: 13,
  ANDROID_SENSOR_START: 14,
  ANDROID_SENSOR_INFO_START: 15,
  ANDROID_SHADING_START: 16,
  ANDROID_STATISTICS_START: 17,
  ANDROID_STATISTICS_INFO_START: 18,
  ANDROID_TONEMAP_START: 19,
  ANDROID_LED_START: 20,
  ANDROID_INFO_START: 21,
  ANDROID_BLACK_LEVEL_START: 22,
  ANDROID_SYNC_START: 23,
  ANDROID_REPROCESS_START: 24,
  ANDROID_DEPTH_START: 25,
  ANDROID_LOGICAL_MULTI_CAMERA_START: 26,
  ANDROID_DISTORTION_CORRECTION_START: 27,
  ANDROID_HEIC_START: 28,
  ANDROID_HEIC_INFO_START: 29,
  ANDROID_AUTOMOTIVE_START: 30,
  ANDROID_AUTOMOTIVE_LENS_START: 31,
};
cros.mojom.CameraMetadataSectionStartSpec = { $: mojo.internal.Enum() };

// Enum: CameraMetadataTag
cros.mojom.CameraMetadataTag = {
  ANDROID_COLOR_CORRECTION_MODE: 0,
  ANDROID_COLOR_CORRECTION_TRANSFORM: 1,
  ANDROID_COLOR_CORRECTION_GAINS: 2,
  ANDROID_COLOR_CORRECTION_ABERRATION_MODE: 3,
  ANDROID_COLOR_CORRECTION_AVAILABLE_ABERRATION_MODES: 4,
  ANDROID_COLOR_CORRECTION_END: 5,
  ANDROID_CONTROL_AE_ANTIBANDING_MODE: 6,
  ANDROID_CONTROL_AE_EXPOSURE_COMPENSATION: 7,
  ANDROID_CONTROL_AE_LOCK: 8,
  ANDROID_CONTROL_AE_MODE: 9,
  ANDROID_CONTROL_AE_REGIONS: 10,
  ANDROID_CONTROL_AE_TARGET_FPS_RANGE: 11,
  ANDROID_CONTROL_AE_PRECAPTURE_TRIGGER: 12,
  ANDROID_CONTROL_AF_MODE: 13,
  ANDROID_CONTROL_AF_REGIONS: 14,
  ANDROID_CONTROL_AF_TRIGGER: 15,
  ANDROID_CONTROL_AWB_LOCK: 16,
  ANDROID_CONTROL_AWB_MODE: 17,
  ANDROID_CONTROL_AWB_REGIONS: 18,
  ANDROID_CONTROL_CAPTURE_INTENT: 19,
  ANDROID_CONTROL_EFFECT_MODE: 20,
  ANDROID_CONTROL_MODE: 21,
  ANDROID_CONTROL_SCENE_MODE: 22,
  ANDROID_CONTROL_VIDEO_STABILIZATION_MODE: 23,
  ANDROID_CONTROL_AE_AVAILABLE_ANTIBANDING_MODES: 24,
  ANDROID_CONTROL_AE_AVAILABLE_MODES: 25,
  ANDROID_CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES: 26,
  ANDROID_CONTROL_AE_COMPENSATION_RANGE: 27,
  ANDROID_CONTROL_AE_COMPENSATION_STEP: 28,
  ANDROID_CONTROL_AF_AVAILABLE_MODES: 29,
  ANDROID_CONTROL_AVAILABLE_EFFECTS: 30,
  ANDROID_CONTROL_AVAILABLE_SCENE_MODES: 31,
  ANDROID_CONTROL_AVAILABLE_VIDEO_STABILIZATION_MODES: 32,
  ANDROID_CONTROL_AWB_AVAILABLE_MODES: 33,
  ANDROID_CONTROL_MAX_REGIONS: 34,
  ANDROID_CONTROL_SCENE_MODE_OVERRIDES: 35,
  ANDROID_CONTROL_AE_PRECAPTURE_ID: 36,
  ANDROID_CONTROL_AE_STATE: 37,
  ANDROID_CONTROL_AF_STATE: 38,
  ANDROID_CONTROL_AF_TRIGGER_ID: 39,
  ANDROID_CONTROL_AWB_STATE: 40,
  ANDROID_CONTROL_AVAILABLE_HIGH_SPEED_VIDEO_CONFIGURATIONS: 41,
  ANDROID_CONTROL_AE_LOCK_AVAILABLE: 42,
  ANDROID_CONTROL_AWB_LOCK_AVAILABLE: 43,
  ANDROID_CONTROL_AVAILABLE_MODES: 44,
  ANDROID_CONTROL_POST_RAW_SENSITIVITY_BOOST_RANGE: 45,
  ANDROID_CONTROL_POST_RAW_SENSITIVITY_BOOST: 46,
  ANDROID_CONTROL_ENABLE_ZSL: 47,
  ANDROID_CONTROL_AF_SCENE_CHANGE: 48,
  ANDROID_CONTROL_AVAILABLE_EXTENDED_SCENE_MODE_MAX_SIZES: 49,
  ANDROID_CONTROL_AVAILABLE_EXTENDED_SCENE_MODE_ZOOM_RATIO_RANGES: 50,
  ANDROID_CONTROL_EXTENDED_SCENE_MODE: 51,
  ANDROID_CONTROL_ZOOM_RATIO_RANGE: 52,
  ANDROID_CONTROL_ZOOM_RATIO: 53,
  ANDROID_CONTROL_AVAILABLE_HIGH_SPEED_VIDEO_CONFIGURATIONS_MAXIMUM_RESOLUTION: 54,
  ANDROID_CONTROL_AF_REGIONS_SET: 55,
  ANDROID_CONTROL_AE_REGIONS_SET: 56,
  ANDROID_CONTROL_AWB_REGIONS_SET: 57,
  ANDROID_CONTROL_END: 58,
  ANDROID_DEMOSAIC_MODE: 59,
  ANDROID_DEMOSAIC_END: 60,
  ANDROID_EDGE_MODE: 61,
  ANDROID_EDGE_STRENGTH: 62,
  ANDROID_EDGE_AVAILABLE_EDGE_MODES: 63,
  ANDROID_EDGE_END: 64,
  ANDROID_FLASH_FIRING_POWER: 65,
  ANDROID_FLASH_FIRING_TIME: 66,
  ANDROID_FLASH_MODE: 67,
  ANDROID_FLASH_COLOR_TEMPERATURE: 68,
  ANDROID_FLASH_MAX_ENERGY: 69,
  ANDROID_FLASH_STATE: 70,
  ANDROID_FLASH_END: 71,
  ANDROID_FLASH_INFO_AVAILABLE: 72,
  ANDROID_FLASH_INFO_CHARGE_DURATION: 73,
  ANDROID_FLASH_INFO_STRENGTH_MAXIMUM_LEVEL: 74,
  ANDROID_FLASH_INFO_STRENGTH_DEFAULT_LEVEL: 75,
  ANDROID_FLASH_INFO_END: 76,
  ANDROID_HOT_PIXEL_MODE: 77,
  ANDROID_HOT_PIXEL_AVAILABLE_HOT_PIXEL_MODES: 78,
  ANDROID_HOT_PIXEL_END: 79,
  ANDROID_JPEG_GPS_COORDINATES: 80,
  ANDROID_JPEG_GPS_PROCESSING_METHOD: 81,
  ANDROID_JPEG_GPS_TIMESTAMP: 82,
  ANDROID_JPEG_ORIENTATION: 83,
  ANDROID_JPEG_QUALITY: 84,
  ANDROID_JPEG_THUMBNAIL_QUALITY: 85,
  ANDROID_JPEG_THUMBNAIL_SIZE: 86,
  ANDROID_JPEG_AVAILABLE_THUMBNAIL_SIZES: 87,
  ANDROID_JPEG_MAX_SIZE: 88,
  ANDROID_JPEG_SIZE: 89,
  ANDROID_JPEG_END: 90,
  ANDROID_LENS_APERTURE: 91,
  ANDROID_LENS_FILTER_DENSITY: 92,
  ANDROID_LENS_FOCAL_LENGTH: 93,
  ANDROID_LENS_FOCUS_DISTANCE: 94,
  ANDROID_LENS_OPTICAL_STABILIZATION_MODE: 95,
  ANDROID_LENS_FACING: 96,
  ANDROID_LENS_POSE_ROTATION: 97,
  ANDROID_LENS_POSE_TRANSLATION: 98,
  ANDROID_LENS_FOCUS_RANGE: 99,
  ANDROID_LENS_STATE: 100,
  ANDROID_LENS_INTRINSIC_CALIBRATION: 101,
  ANDROID_LENS_RADIAL_DISTORTION: 102,
  ANDROID_LENS_POSE_REFERENCE: 103,
  ANDROID_LENS_DISTORTION: 104,
  ANDROID_LENS_DISTORTION_MAXIMUM_RESOLUTION: 105,
  ANDROID_LENS_INTRINSIC_CALIBRATION_MAXIMUM_RESOLUTION: 106,
  ANDROID_LENS_END: 107,
  ANDROID_LENS_INFO_AVAILABLE_APERTURES: 108,
  ANDROID_LENS_INFO_AVAILABLE_FILTER_DENSITIES: 109,
  ANDROID_LENS_INFO_AVAILABLE_FOCAL_LENGTHS: 110,
  ANDROID_LENS_INFO_AVAILABLE_OPTICAL_STABILIZATION: 111,
  ANDROID_LENS_INFO_HYPERFOCAL_DISTANCE: 112,
  ANDROID_LENS_INFO_MINIMUM_FOCUS_DISTANCE: 113,
  ANDROID_LENS_INFO_SHADING_MAP_SIZE: 114,
  ANDROID_LENS_INFO_FOCUS_DISTANCE_CALIBRATION: 115,
  ANDROID_LENS_INFO_END: 116,
  ANDROID_NOISE_REDUCTION_MODE: 117,
  ANDROID_NOISE_REDUCTION_STRENGTH: 118,
  ANDROID_NOISE_REDUCTION_AVAILABLE_NOISE_REDUCTION_MODES: 119,
  ANDROID_NOISE_REDUCTION_END: 120,
  ANDROID_QUIRKS_METERING_CROP_REGION: 121,
  ANDROID_QUIRKS_TRIGGER_AF_WITH_AUTO: 122,
  ANDROID_QUIRKS_USE_ZSL_FORMAT: 123,
  ANDROID_QUIRKS_USE_PARTIAL_RESULT: 124,
  ANDROID_QUIRKS_PARTIAL_RESULT: 125,
  ANDROID_QUIRKS_END: 126,
  ANDROID_REQUEST_FRAME_COUNT: 127,
  ANDROID_REQUEST_ID: 128,
  ANDROID_REQUEST_INPUT_STREAMS: 129,
  ANDROID_REQUEST_METADATA_MODE: 130,
  ANDROID_REQUEST_OUTPUT_STREAMS: 131,
  ANDROID_REQUEST_TYPE: 132,
  ANDROID_REQUEST_MAX_NUM_OUTPUT_STREAMS: 133,
  ANDROID_REQUEST_MAX_NUM_REPROCESS_STREAMS: 134,
  ANDROID_REQUEST_MAX_NUM_INPUT_STREAMS: 135,
  ANDROID_REQUEST_PIPELINE_DEPTH: 136,
  ANDROID_REQUEST_PIPELINE_MAX_DEPTH: 137,
  ANDROID_REQUEST_PARTIAL_RESULT_COUNT: 138,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES: 139,
  ANDROID_REQUEST_AVAILABLE_REQUEST_KEYS: 140,
  ANDROID_REQUEST_AVAILABLE_RESULT_KEYS: 141,
  ANDROID_REQUEST_AVAILABLE_CHARACTERISTICS_KEYS: 142,
  ANDROID_REQUEST_AVAILABLE_SESSION_KEYS: 143,
  ANDROID_REQUEST_AVAILABLE_PHYSICAL_CAMERA_REQUEST_KEYS: 144,
  ANDROID_REQUEST_CHARACTERISTIC_KEYS_NEEDING_PERMISSION: 145,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP: 146,
  ANDROID_REQUEST_RECOMMENDED_TEN_BIT_DYNAMIC_RANGE_PROFILE: 147,
  ANDROID_REQUEST_END: 148,
  ANDROID_SCALER_CROP_REGION: 149,
  ANDROID_SCALER_AVAILABLE_FORMATS: 150,
  ANDROID_SCALER_AVAILABLE_JPEG_MIN_DURATIONS: 151,
  ANDROID_SCALER_AVAILABLE_JPEG_SIZES: 152,
  ANDROID_SCALER_AVAILABLE_MAX_DIGITAL_ZOOM: 153,
  ANDROID_SCALER_AVAILABLE_PROCESSED_MIN_DURATIONS: 154,
  ANDROID_SCALER_AVAILABLE_PROCESSED_SIZES: 155,
  ANDROID_SCALER_AVAILABLE_RAW_MIN_DURATIONS: 156,
  ANDROID_SCALER_AVAILABLE_RAW_SIZES: 157,
  ANDROID_SCALER_AVAILABLE_INPUT_OUTPUT_FORMATS_MAP: 158,
  ANDROID_SCALER_AVAILABLE_STREAM_CONFIGURATIONS: 159,
  ANDROID_SCALER_AVAILABLE_MIN_FRAME_DURATIONS: 160,
  ANDROID_SCALER_AVAILABLE_STALL_DURATIONS: 161,
  ANDROID_SCALER_CROPPING_TYPE: 162,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS: 163,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_INPUT_OUTPUT_FORMATS_MAP: 164,
  ANDROID_SCALER_AVAILABLE_ROTATE_AND_CROP_MODES: 165,
  ANDROID_SCALER_ROTATE_AND_CROP: 166,
  ANDROID_SCALER_DEFAULT_SECURE_IMAGE_SIZE: 167,
  ANDROID_SCALER_PHYSICAL_CAMERA_MULTI_RESOLUTION_STREAM_CONFIGURATIONS: 168,
  ANDROID_SCALER_AVAILABLE_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION: 169,
  ANDROID_SCALER_AVAILABLE_MIN_FRAME_DURATIONS_MAXIMUM_RESOLUTION: 170,
  ANDROID_SCALER_AVAILABLE_STALL_DURATIONS_MAXIMUM_RESOLUTION: 171,
  ANDROID_SCALER_AVAILABLE_INPUT_OUTPUT_FORMATS_MAP_MAXIMUM_RESOLUTION: 172,
  ANDROID_SCALER_MULTI_RESOLUTION_STREAM_SUPPORTED: 173,
  ANDROID_SCALER_CROP_REGION_SET: 174,
  ANDROID_SCALER_AVAILABLE_STREAM_USE_CASES: 175,
  ANDROID_SCALER_END: 176,
  ANDROID_SENSOR_EXPOSURE_TIME: 177,
  ANDROID_SENSOR_FRAME_DURATION: 178,
  ANDROID_SENSOR_SENSITIVITY: 179,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1: 180,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT2: 181,
  ANDROID_SENSOR_CALIBRATION_TRANSFORM1: 182,
  ANDROID_SENSOR_CALIBRATION_TRANSFORM2: 183,
  ANDROID_SENSOR_COLOR_TRANSFORM1: 184,
  ANDROID_SENSOR_COLOR_TRANSFORM2: 185,
  ANDROID_SENSOR_FORWARD_MATRIX1: 186,
  ANDROID_SENSOR_FORWARD_MATRIX2: 187,
  ANDROID_SENSOR_BASE_GAIN_FACTOR: 188,
  ANDROID_SENSOR_BLACK_LEVEL_PATTERN: 189,
  ANDROID_SENSOR_MAX_ANALOG_SENSITIVITY: 190,
  ANDROID_SENSOR_ORIENTATION: 191,
  ANDROID_SENSOR_PROFILE_HUE_SAT_MAP_DIMENSIONS: 192,
  ANDROID_SENSOR_TIMESTAMP: 193,
  ANDROID_SENSOR_TEMPERATURE: 194,
  ANDROID_SENSOR_NEUTRAL_COLOR_POINT: 195,
  ANDROID_SENSOR_NOISE_PROFILE: 196,
  ANDROID_SENSOR_PROFILE_HUE_SAT_MAP: 197,
  ANDROID_SENSOR_PROFILE_TONE_CURVE: 198,
  ANDROID_SENSOR_GREEN_SPLIT: 199,
  ANDROID_SENSOR_TEST_PATTERN_DATA: 200,
  ANDROID_SENSOR_TEST_PATTERN_MODE: 201,
  ANDROID_SENSOR_AVAILABLE_TEST_PATTERN_MODES: 202,
  ANDROID_SENSOR_ROLLING_SHUTTER_SKEW: 203,
  ANDROID_SENSOR_OPTICAL_BLACK_REGIONS: 204,
  ANDROID_SENSOR_DYNAMIC_BLACK_LEVEL: 205,
  ANDROID_SENSOR_DYNAMIC_WHITE_LEVEL: 206,
  ANDROID_SENSOR_OPAQUE_RAW_SIZE: 207,
  ANDROID_SENSOR_OPAQUE_RAW_SIZE_MAXIMUM_RESOLUTION: 208,
  ANDROID_SENSOR_PIXEL_MODE: 209,
  ANDROID_SENSOR_RAW_BINNING_FACTOR_USED: 210,
  ANDROID_SENSOR_END: 211,
  ANDROID_SENSOR_INFO_ACTIVE_ARRAY_SIZE: 212,
  ANDROID_SENSOR_INFO_SENSITIVITY_RANGE: 213,
  ANDROID_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT: 214,
  ANDROID_SENSOR_INFO_EXPOSURE_TIME_RANGE: 215,
  ANDROID_SENSOR_INFO_MAX_FRAME_DURATION: 216,
  ANDROID_SENSOR_INFO_PHYSICAL_SIZE: 217,
  ANDROID_SENSOR_INFO_PIXEL_ARRAY_SIZE: 218,
  ANDROID_SENSOR_INFO_WHITE_LEVEL: 219,
  ANDROID_SENSOR_INFO_TIMESTAMP_SOURCE: 220,
  ANDROID_SENSOR_INFO_LENS_SHADING_APPLIED: 221,
  ANDROID_SENSOR_INFO_PRE_CORRECTION_ACTIVE_ARRAY_SIZE: 222,
  ANDROID_SENSOR_INFO_ACTIVE_ARRAY_SIZE_MAXIMUM_RESOLUTION: 223,
  ANDROID_SENSOR_INFO_PIXEL_ARRAY_SIZE_MAXIMUM_RESOLUTION: 224,
  ANDROID_SENSOR_INFO_PRE_CORRECTION_ACTIVE_ARRAY_SIZE_MAXIMUM_RESOLUTION: 225,
  ANDROID_SENSOR_INFO_BINNING_FACTOR: 226,
  ANDROID_SENSOR_INFO_END: 227,
  ANDROID_SHADING_MODE: 228,
  ANDROID_SHADING_STRENGTH: 229,
  ANDROID_SHADING_AVAILABLE_MODES: 230,
  ANDROID_SHADING_END: 231,
  ANDROID_STATISTICS_FACE_DETECT_MODE: 232,
  ANDROID_STATISTICS_HISTOGRAM_MODE: 233,
  ANDROID_STATISTICS_SHARPNESS_MAP_MODE: 234,
  ANDROID_STATISTICS_HOT_PIXEL_MAP_MODE: 235,
  ANDROID_STATISTICS_FACE_IDS: 236,
  ANDROID_STATISTICS_FACE_LANDMARKS: 237,
  ANDROID_STATISTICS_FACE_RECTANGLES: 238,
  ANDROID_STATISTICS_FACE_SCORES: 239,
  ANDROID_STATISTICS_HISTOGRAM: 240,
  ANDROID_STATISTICS_SHARPNESS_MAP: 241,
  ANDROID_STATISTICS_LENS_SHADING_CORRECTION_MAP: 242,
  ANDROID_STATISTICS_LENS_SHADING_MAP: 243,
  ANDROID_STATISTICS_PREDICTED_COLOR_GAINS: 244,
  ANDROID_STATISTICS_PREDICTED_COLOR_TRANSFORM: 245,
  ANDROID_STATISTICS_SCENE_FLICKER: 246,
  ANDROID_STATISTICS_HOT_PIXEL_MAP: 247,
  ANDROID_STATISTICS_LENS_SHADING_MAP_MODE: 248,
  ANDROID_STATISTICS_OIS_DATA_MODE: 249,
  ANDROID_STATISTICS_OIS_TIMESTAMPS: 250,
  ANDROID_STATISTICS_OIS_X_SHIFTS: 251,
  ANDROID_STATISTICS_OIS_Y_SHIFTS: 252,
  ANDROID_STATISTICS_END: 253,
  ANDROID_STATISTICS_INFO_AVAILABLE_FACE_DETECT_MODES: 254,
  ANDROID_STATISTICS_INFO_HISTOGRAM_BUCKET_COUNT: 255,
  ANDROID_STATISTICS_INFO_MAX_FACE_COUNT: 256,
  ANDROID_STATISTICS_INFO_MAX_HISTOGRAM_COUNT: 257,
  ANDROID_STATISTICS_INFO_MAX_SHARPNESS_MAP_VALUE: 258,
  ANDROID_STATISTICS_INFO_SHARPNESS_MAP_SIZE: 259,
  ANDROID_STATISTICS_INFO_AVAILABLE_HOT_PIXEL_MAP_MODES: 260,
  ANDROID_STATISTICS_INFO_AVAILABLE_LENS_SHADING_MAP_MODES: 261,
  ANDROID_STATISTICS_INFO_AVAILABLE_OIS_DATA_MODES: 262,
  ANDROID_STATISTICS_INFO_END: 263,
  ANDROID_TONEMAP_CURVE_BLUE: 264,
  ANDROID_TONEMAP_CURVE_GREEN: 265,
  ANDROID_TONEMAP_CURVE_RED: 266,
  ANDROID_TONEMAP_MODE: 267,
  ANDROID_TONEMAP_MAX_CURVE_POINTS: 268,
  ANDROID_TONEMAP_AVAILABLE_TONE_MAP_MODES: 269,
  ANDROID_TONEMAP_GAMMA: 270,
  ANDROID_TONEMAP_PRESET_CURVE: 271,
  ANDROID_TONEMAP_END: 272,
  ANDROID_LED_TRANSMIT: 273,
  ANDROID_LED_AVAILABLE_LEDS: 274,
  ANDROID_LED_END: 275,
  ANDROID_INFO_SUPPORTED_HARDWARE_LEVEL: 276,
  ANDROID_INFO_VERSION: 277,
  ANDROID_INFO_SUPPORTED_BUFFER_MANAGEMENT_VERSION: 278,
  ANDROID_INFO_DEVICE_STATE_ORIENTATIONS: 279,
  ANDROID_INFO_END: 280,
  ANDROID_BLACK_LEVEL_LOCK: 281,
  ANDROID_BLACK_LEVEL_END: 282,
  ANDROID_SYNC_FRAME_NUMBER: 283,
  ANDROID_SYNC_MAX_LATENCY: 284,
  ANDROID_SYNC_END: 285,
  ANDROID_REPROCESS_EFFECTIVE_EXPOSURE_FACTOR: 286,
  ANDROID_REPROCESS_MAX_CAPTURE_STALL: 287,
  ANDROID_REPROCESS_END: 288,
  ANDROID_DEPTH_MAX_DEPTH_SAMPLES: 289,
  ANDROID_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS: 290,
  ANDROID_DEPTH_AVAILABLE_DEPTH_MIN_FRAME_DURATIONS: 291,
  ANDROID_DEPTH_AVAILABLE_DEPTH_STALL_DURATIONS: 292,
  ANDROID_DEPTH_DEPTH_IS_EXCLUSIVE: 293,
  ANDROID_DEPTH_AVAILABLE_RECOMMENDED_DEPTH_STREAM_CONFIGURATIONS: 294,
  ANDROID_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STREAM_CONFIGURATIONS: 295,
  ANDROID_DEPTH_AVAILABLE_DYNAMIC_DEPTH_MIN_FRAME_DURATIONS: 296,
  ANDROID_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STALL_DURATIONS: 297,
  ANDROID_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION: 298,
  ANDROID_DEPTH_AVAILABLE_DEPTH_MIN_FRAME_DURATIONS_MAXIMUM_RESOLUTION: 299,
  ANDROID_DEPTH_AVAILABLE_DEPTH_STALL_DURATIONS_MAXIMUM_RESOLUTION: 300,
  ANDROID_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION: 301,
  ANDROID_DEPTH_AVAILABLE_DYNAMIC_DEPTH_MIN_FRAME_DURATIONS_MAXIMUM_RESOLUTION: 302,
  ANDROID_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STALL_DURATIONS_MAXIMUM_RESOLUTION: 303,
  ANDROID_DEPTH_END: 304,
  ANDROID_LOGICAL_MULTI_CAMERA_PHYSICAL_IDS: 305,
  ANDROID_LOGICAL_MULTI_CAMERA_SENSOR_SYNC_TYPE: 306,
  ANDROID_LOGICAL_MULTI_CAMERA_ACTIVE_PHYSICAL_ID: 307,
  ANDROID_LOGICAL_MULTI_CAMERA_END: 308,
  ANDROID_DISTORTION_CORRECTION_MODE: 309,
  ANDROID_DISTORTION_CORRECTION_AVAILABLE_MODES: 310,
  ANDROID_DISTORTION_CORRECTION_END: 311,
  ANDROID_HEIC_AVAILABLE_HEIC_STREAM_CONFIGURATIONS: 312,
  ANDROID_HEIC_AVAILABLE_HEIC_MIN_FRAME_DURATIONS: 313,
  ANDROID_HEIC_AVAILABLE_HEIC_STALL_DURATIONS: 314,
  ANDROID_HEIC_AVAILABLE_HEIC_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION: 315,
  ANDROID_HEIC_AVAILABLE_HEIC_MIN_FRAME_DURATIONS_MAXIMUM_RESOLUTION: 316,
  ANDROID_HEIC_AVAILABLE_HEIC_STALL_DURATIONS_MAXIMUM_RESOLUTION: 317,
  ANDROID_HEIC_END: 318,
  ANDROID_HEIC_INFO_SUPPORTED: 319,
  ANDROID_HEIC_INFO_MAX_JPEG_APP_SEGMENTS_COUNT: 320,
  ANDROID_HEIC_INFO_END: 321,
  ANDROID_AUTOMOTIVE_LOCATION: 322,
  ANDROID_AUTOMOTIVE_END: 323,
  ANDROID_AUTOMOTIVE_LENS_FACING: 324,
  ANDROID_AUTOMOTIVE_LENS_END: 325,
};
cros.mojom.CameraMetadataTagSpec = { $: mojo.internal.Enum() };

// Enum: AndroidColorCorrectionMode
cros.mojom.AndroidColorCorrectionMode = {
  ANDROID_COLOR_CORRECTION_MODE_TRANSFORM_MATRIX: 0,
  ANDROID_COLOR_CORRECTION_MODE_FAST: 1,
  ANDROID_COLOR_CORRECTION_MODE_HIGH_QUALITY: 2,
};
cros.mojom.AndroidColorCorrectionModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidColorCorrectionAberrationMode
cros.mojom.AndroidColorCorrectionAberrationMode = {
  ANDROID_COLOR_CORRECTION_ABERRATION_MODE_OFF: 0,
  ANDROID_COLOR_CORRECTION_ABERRATION_MODE_FAST: 1,
  ANDROID_COLOR_CORRECTION_ABERRATION_MODE_HIGH_QUALITY: 2,
};
cros.mojom.AndroidColorCorrectionAberrationModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAeAntibandingMode
cros.mojom.AndroidControlAeAntibandingMode = {
  ANDROID_CONTROL_AE_ANTIBANDING_MODE_OFF: 0,
  ANDROID_CONTROL_AE_ANTIBANDING_MODE_50HZ: 1,
  ANDROID_CONTROL_AE_ANTIBANDING_MODE_60HZ: 2,
  ANDROID_CONTROL_AE_ANTIBANDING_MODE_AUTO: 3,
};
cros.mojom.AndroidControlAeAntibandingModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAeLock
cros.mojom.AndroidControlAeLock = {
  ANDROID_CONTROL_AE_LOCK_OFF: 0,
  ANDROID_CONTROL_AE_LOCK_ON: 1,
};
cros.mojom.AndroidControlAeLockSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAeMode
cros.mojom.AndroidControlAeMode = {
  ANDROID_CONTROL_AE_MODE_OFF: 0,
  ANDROID_CONTROL_AE_MODE_ON: 1,
  ANDROID_CONTROL_AE_MODE_ON_AUTO_FLASH: 2,
  ANDROID_CONTROL_AE_MODE_ON_ALWAYS_FLASH: 3,
  ANDROID_CONTROL_AE_MODE_ON_AUTO_FLASH_REDEYE: 4,
  ANDROID_CONTROL_AE_MODE_ON_EXTERNAL_FLASH: 5,
};
cros.mojom.AndroidControlAeModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAePrecaptureTrigger
cros.mojom.AndroidControlAePrecaptureTrigger = {
  ANDROID_CONTROL_AE_PRECAPTURE_TRIGGER_IDLE: 0,
  ANDROID_CONTROL_AE_PRECAPTURE_TRIGGER_START: 1,
  ANDROID_CONTROL_AE_PRECAPTURE_TRIGGER_CANCEL: 2,
};
cros.mojom.AndroidControlAePrecaptureTriggerSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAfMode
cros.mojom.AndroidControlAfMode = {
  ANDROID_CONTROL_AF_MODE_OFF: 0,
  ANDROID_CONTROL_AF_MODE_AUTO: 1,
  ANDROID_CONTROL_AF_MODE_MACRO: 2,
  ANDROID_CONTROL_AF_MODE_CONTINUOUS_VIDEO: 3,
  ANDROID_CONTROL_AF_MODE_CONTINUOUS_PICTURE: 4,
  ANDROID_CONTROL_AF_MODE_EDOF: 5,
};
cros.mojom.AndroidControlAfModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAfTrigger
cros.mojom.AndroidControlAfTrigger = {
  ANDROID_CONTROL_AF_TRIGGER_IDLE: 0,
  ANDROID_CONTROL_AF_TRIGGER_START: 1,
  ANDROID_CONTROL_AF_TRIGGER_CANCEL: 2,
};
cros.mojom.AndroidControlAfTriggerSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAwbLock
cros.mojom.AndroidControlAwbLock = {
  ANDROID_CONTROL_AWB_LOCK_OFF: 0,
  ANDROID_CONTROL_AWB_LOCK_ON: 1,
};
cros.mojom.AndroidControlAwbLockSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAwbMode
cros.mojom.AndroidControlAwbMode = {
  ANDROID_CONTROL_AWB_MODE_OFF: 0,
  ANDROID_CONTROL_AWB_MODE_AUTO: 1,
  ANDROID_CONTROL_AWB_MODE_INCANDESCENT: 2,
  ANDROID_CONTROL_AWB_MODE_FLUORESCENT: 3,
  ANDROID_CONTROL_AWB_MODE_WARM_FLUORESCENT: 4,
  ANDROID_CONTROL_AWB_MODE_DAYLIGHT: 5,
  ANDROID_CONTROL_AWB_MODE_CLOUDY_DAYLIGHT: 6,
  ANDROID_CONTROL_AWB_MODE_TWILIGHT: 7,
  ANDROID_CONTROL_AWB_MODE_SHADE: 8,
};
cros.mojom.AndroidControlAwbModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlCaptureIntent
cros.mojom.AndroidControlCaptureIntent = {
  ANDROID_CONTROL_CAPTURE_INTENT_CUSTOM: 0,
  ANDROID_CONTROL_CAPTURE_INTENT_PREVIEW: 1,
  ANDROID_CONTROL_CAPTURE_INTENT_STILL_CAPTURE: 2,
  ANDROID_CONTROL_CAPTURE_INTENT_VIDEO_RECORD: 3,
  ANDROID_CONTROL_CAPTURE_INTENT_VIDEO_SNAPSHOT: 4,
  ANDROID_CONTROL_CAPTURE_INTENT_ZERO_SHUTTER_LAG: 5,
  ANDROID_CONTROL_CAPTURE_INTENT_MANUAL: 6,
  ANDROID_CONTROL_CAPTURE_INTENT_MOTION_TRACKING: 7,
};
cros.mojom.AndroidControlCaptureIntentSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlEffectMode
cros.mojom.AndroidControlEffectMode = {
  ANDROID_CONTROL_EFFECT_MODE_OFF: 0,
  ANDROID_CONTROL_EFFECT_MODE_MONO: 1,
  ANDROID_CONTROL_EFFECT_MODE_NEGATIVE: 2,
  ANDROID_CONTROL_EFFECT_MODE_SOLARIZE: 3,
  ANDROID_CONTROL_EFFECT_MODE_SEPIA: 4,
  ANDROID_CONTROL_EFFECT_MODE_POSTERIZE: 5,
  ANDROID_CONTROL_EFFECT_MODE_WHITEBOARD: 6,
  ANDROID_CONTROL_EFFECT_MODE_BLACKBOARD: 7,
  ANDROID_CONTROL_EFFECT_MODE_AQUA: 8,
};
cros.mojom.AndroidControlEffectModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlMode
cros.mojom.AndroidControlMode = {
  ANDROID_CONTROL_MODE_OFF: 0,
  ANDROID_CONTROL_MODE_AUTO: 1,
  ANDROID_CONTROL_MODE_USE_SCENE_MODE: 2,
  ANDROID_CONTROL_MODE_OFF_KEEP_STATE: 3,
  ANDROID_CONTROL_MODE_USE_EXTENDED_SCENE_MODE: 4,
};
cros.mojom.AndroidControlModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlSceneMode
cros.mojom.AndroidControlSceneMode = {
  ANDROID_CONTROL_SCENE_MODE_DISABLED: 0,
  ANDROID_CONTROL_SCENE_MODE_FACE_PRIORITY: 1,
  ANDROID_CONTROL_SCENE_MODE_ACTION: 2,
  ANDROID_CONTROL_SCENE_MODE_PORTRAIT: 3,
  ANDROID_CONTROL_SCENE_MODE_LANDSCAPE: 4,
  ANDROID_CONTROL_SCENE_MODE_NIGHT: 5,
  ANDROID_CONTROL_SCENE_MODE_NIGHT_PORTRAIT: 6,
  ANDROID_CONTROL_SCENE_MODE_THEATRE: 7,
  ANDROID_CONTROL_SCENE_MODE_BEACH: 8,
  ANDROID_CONTROL_SCENE_MODE_SNOW: 9,
  ANDROID_CONTROL_SCENE_MODE_SUNSET: 10,
  ANDROID_CONTROL_SCENE_MODE_STEADYPHOTO: 11,
  ANDROID_CONTROL_SCENE_MODE_FIREWORKS: 12,
  ANDROID_CONTROL_SCENE_MODE_SPORTS: 13,
  ANDROID_CONTROL_SCENE_MODE_PARTY: 14,
  ANDROID_CONTROL_SCENE_MODE_CANDLELIGHT: 15,
  ANDROID_CONTROL_SCENE_MODE_BARCODE: 16,
  ANDROID_CONTROL_SCENE_MODE_HIGH_SPEED_VIDEO: 17,
  ANDROID_CONTROL_SCENE_MODE_HDR: 18,
  ANDROID_CONTROL_SCENE_MODE_FACE_PRIORITY_LOW_LIGHT: 19,
  ANDROID_CONTROL_SCENE_MODE_DEVICE_CUSTOM_START: 20,
  ANDROID_CONTROL_SCENE_MODE_DEVICE_CUSTOM_END: 21,
};
cros.mojom.AndroidControlSceneModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlVideoStabilizationMode
cros.mojom.AndroidControlVideoStabilizationMode = {
  ANDROID_CONTROL_VIDEO_STABILIZATION_MODE_OFF: 0,
  ANDROID_CONTROL_VIDEO_STABILIZATION_MODE_ON: 1,
  ANDROID_CONTROL_VIDEO_STABILIZATION_MODE_PREVIEW_STABILIZATION: 2,
};
cros.mojom.AndroidControlVideoStabilizationModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAeState
cros.mojom.AndroidControlAeState = {
  ANDROID_CONTROL_AE_STATE_INACTIVE: 0,
  ANDROID_CONTROL_AE_STATE_SEARCHING: 1,
  ANDROID_CONTROL_AE_STATE_CONVERGED: 2,
  ANDROID_CONTROL_AE_STATE_LOCKED: 3,
  ANDROID_CONTROL_AE_STATE_FLASH_REQUIRED: 4,
  ANDROID_CONTROL_AE_STATE_PRECAPTURE: 5,
};
cros.mojom.AndroidControlAeStateSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAfState
cros.mojom.AndroidControlAfState = {
  ANDROID_CONTROL_AF_STATE_INACTIVE: 0,
  ANDROID_CONTROL_AF_STATE_PASSIVE_SCAN: 1,
  ANDROID_CONTROL_AF_STATE_PASSIVE_FOCUSED: 2,
  ANDROID_CONTROL_AF_STATE_ACTIVE_SCAN: 3,
  ANDROID_CONTROL_AF_STATE_FOCUSED_LOCKED: 4,
  ANDROID_CONTROL_AF_STATE_NOT_FOCUSED_LOCKED: 5,
  ANDROID_CONTROL_AF_STATE_PASSIVE_UNFOCUSED: 6,
};
cros.mojom.AndroidControlAfStateSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAwbState
cros.mojom.AndroidControlAwbState = {
  ANDROID_CONTROL_AWB_STATE_INACTIVE: 0,
  ANDROID_CONTROL_AWB_STATE_SEARCHING: 1,
  ANDROID_CONTROL_AWB_STATE_CONVERGED: 2,
  ANDROID_CONTROL_AWB_STATE_LOCKED: 3,
};
cros.mojom.AndroidControlAwbStateSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAeLockAvailable
cros.mojom.AndroidControlAeLockAvailable = {
  ANDROID_CONTROL_AE_LOCK_AVAILABLE_FALSE: 0,
  ANDROID_CONTROL_AE_LOCK_AVAILABLE_TRUE: 1,
};
cros.mojom.AndroidControlAeLockAvailableSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAwbLockAvailable
cros.mojom.AndroidControlAwbLockAvailable = {
  ANDROID_CONTROL_AWB_LOCK_AVAILABLE_FALSE: 0,
  ANDROID_CONTROL_AWB_LOCK_AVAILABLE_TRUE: 1,
};
cros.mojom.AndroidControlAwbLockAvailableSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlEnableZsl
cros.mojom.AndroidControlEnableZsl = {
  ANDROID_CONTROL_ENABLE_ZSL_FALSE: 0,
  ANDROID_CONTROL_ENABLE_ZSL_TRUE: 1,
};
cros.mojom.AndroidControlEnableZslSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAfSceneChange
cros.mojom.AndroidControlAfSceneChange = {
  ANDROID_CONTROL_AF_SCENE_CHANGE_NOT_DETECTED: 0,
  ANDROID_CONTROL_AF_SCENE_CHANGE_DETECTED: 1,
};
cros.mojom.AndroidControlAfSceneChangeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlExtendedSceneMode
cros.mojom.AndroidControlExtendedSceneMode = {
  ANDROID_CONTROL_EXTENDED_SCENE_MODE_DISABLED: 0,
  ANDROID_CONTROL_EXTENDED_SCENE_MODE_BOKEH_STILL_CAPTURE: 1,
  ANDROID_CONTROL_EXTENDED_SCENE_MODE_BOKEH_CONTINUOUS: 2,
  ANDROID_CONTROL_EXTENDED_SCENE_MODE_VENDOR_START: 3,
};
cros.mojom.AndroidControlExtendedSceneModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAfRegionsSet
cros.mojom.AndroidControlAfRegionsSet = {
  ANDROID_CONTROL_AF_REGIONS_SET_FALSE: 0,
  ANDROID_CONTROL_AF_REGIONS_SET_TRUE: 1,
};
cros.mojom.AndroidControlAfRegionsSetSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAeRegionsSet
cros.mojom.AndroidControlAeRegionsSet = {
  ANDROID_CONTROL_AE_REGIONS_SET_FALSE: 0,
  ANDROID_CONTROL_AE_REGIONS_SET_TRUE: 1,
};
cros.mojom.AndroidControlAeRegionsSetSpec = { $: mojo.internal.Enum() };

// Enum: AndroidControlAwbRegionsSet
cros.mojom.AndroidControlAwbRegionsSet = {
  ANDROID_CONTROL_AWB_REGIONS_SET_FALSE: 0,
  ANDROID_CONTROL_AWB_REGIONS_SET_TRUE: 1,
};
cros.mojom.AndroidControlAwbRegionsSetSpec = { $: mojo.internal.Enum() };

// Enum: AndroidDemosaicMode
cros.mojom.AndroidDemosaicMode = {
  ANDROID_DEMOSAIC_MODE_FAST: 0,
  ANDROID_DEMOSAIC_MODE_HIGH_QUALITY: 1,
};
cros.mojom.AndroidDemosaicModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidEdgeMode
cros.mojom.AndroidEdgeMode = {
  ANDROID_EDGE_MODE_OFF: 0,
  ANDROID_EDGE_MODE_FAST: 1,
  ANDROID_EDGE_MODE_HIGH_QUALITY: 2,
  ANDROID_EDGE_MODE_ZERO_SHUTTER_LAG: 3,
};
cros.mojom.AndroidEdgeModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidFlashMode
cros.mojom.AndroidFlashMode = {
  ANDROID_FLASH_MODE_OFF: 0,
  ANDROID_FLASH_MODE_SINGLE: 1,
  ANDROID_FLASH_MODE_TORCH: 2,
};
cros.mojom.AndroidFlashModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidFlashState
cros.mojom.AndroidFlashState = {
  ANDROID_FLASH_STATE_UNAVAILABLE: 0,
  ANDROID_FLASH_STATE_CHARGING: 1,
  ANDROID_FLASH_STATE_READY: 2,
  ANDROID_FLASH_STATE_FIRED: 3,
  ANDROID_FLASH_STATE_PARTIAL: 4,
};
cros.mojom.AndroidFlashStateSpec = { $: mojo.internal.Enum() };

// Enum: AndroidFlashInfoAvailable
cros.mojom.AndroidFlashInfoAvailable = {
  ANDROID_FLASH_INFO_AVAILABLE_FALSE: 0,
  ANDROID_FLASH_INFO_AVAILABLE_TRUE: 1,
};
cros.mojom.AndroidFlashInfoAvailableSpec = { $: mojo.internal.Enum() };

// Enum: AndroidHotPixelMode
cros.mojom.AndroidHotPixelMode = {
  ANDROID_HOT_PIXEL_MODE_OFF: 0,
  ANDROID_HOT_PIXEL_MODE_FAST: 1,
  ANDROID_HOT_PIXEL_MODE_HIGH_QUALITY: 2,
};
cros.mojom.AndroidHotPixelModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidLensOpticalStabilizationMode
cros.mojom.AndroidLensOpticalStabilizationMode = {
  ANDROID_LENS_OPTICAL_STABILIZATION_MODE_OFF: 0,
  ANDROID_LENS_OPTICAL_STABILIZATION_MODE_ON: 1,
};
cros.mojom.AndroidLensOpticalStabilizationModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidLensFacing
cros.mojom.AndroidLensFacing = {
  ANDROID_LENS_FACING_FRONT: 0,
  ANDROID_LENS_FACING_BACK: 1,
  ANDROID_LENS_FACING_EXTERNAL: 2,
};
cros.mojom.AndroidLensFacingSpec = { $: mojo.internal.Enum() };

// Enum: AndroidLensState
cros.mojom.AndroidLensState = {
  ANDROID_LENS_STATE_STATIONARY: 0,
  ANDROID_LENS_STATE_MOVING: 1,
};
cros.mojom.AndroidLensStateSpec = { $: mojo.internal.Enum() };

// Enum: AndroidLensPoseReference
cros.mojom.AndroidLensPoseReference = {
  ANDROID_LENS_POSE_REFERENCE_PRIMARY_CAMERA: 0,
  ANDROID_LENS_POSE_REFERENCE_GYROSCOPE: 1,
  ANDROID_LENS_POSE_REFERENCE_UNDEFINED: 2,
  ANDROID_LENS_POSE_REFERENCE_AUTOMOTIVE: 3,
};
cros.mojom.AndroidLensPoseReferenceSpec = { $: mojo.internal.Enum() };

// Enum: AndroidLensInfoFocusDistanceCalibration
cros.mojom.AndroidLensInfoFocusDistanceCalibration = {
  ANDROID_LENS_INFO_FOCUS_DISTANCE_CALIBRATION_UNCALIBRATED: 0,
  ANDROID_LENS_INFO_FOCUS_DISTANCE_CALIBRATION_APPROXIMATE: 1,
  ANDROID_LENS_INFO_FOCUS_DISTANCE_CALIBRATION_CALIBRATED: 2,
};
cros.mojom.AndroidLensInfoFocusDistanceCalibrationSpec = { $: mojo.internal.Enum() };

// Enum: AndroidNoiseReductionMode
cros.mojom.AndroidNoiseReductionMode = {
  ANDROID_NOISE_REDUCTION_MODE_OFF: 0,
  ANDROID_NOISE_REDUCTION_MODE_FAST: 1,
  ANDROID_NOISE_REDUCTION_MODE_HIGH_QUALITY: 2,
  ANDROID_NOISE_REDUCTION_MODE_MINIMAL: 3,
  ANDROID_NOISE_REDUCTION_MODE_ZERO_SHUTTER_LAG: 4,
};
cros.mojom.AndroidNoiseReductionModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidQuirksPartialResult
cros.mojom.AndroidQuirksPartialResult = {
  ANDROID_QUIRKS_PARTIAL_RESULT_FINAL: 0,
  ANDROID_QUIRKS_PARTIAL_RESULT_PARTIAL: 1,
};
cros.mojom.AndroidQuirksPartialResultSpec = { $: mojo.internal.Enum() };

// Enum: AndroidRequestMetadataMode
cros.mojom.AndroidRequestMetadataMode = {
  ANDROID_REQUEST_METADATA_MODE_NONE: 0,
  ANDROID_REQUEST_METADATA_MODE_FULL: 1,
};
cros.mojom.AndroidRequestMetadataModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidRequestType
cros.mojom.AndroidRequestType = {
  ANDROID_REQUEST_TYPE_CAPTURE: 0,
  ANDROID_REQUEST_TYPE_REPROCESS: 1,
};
cros.mojom.AndroidRequestTypeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidRequestAvailableCapabilities
cros.mojom.AndroidRequestAvailableCapabilities = {
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_BACKWARD_COMPATIBLE: 0,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_MANUAL_SENSOR: 1,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_MANUAL_POST_PROCESSING: 2,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_RAW: 3,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_PRIVATE_REPROCESSING: 4,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_READ_SENSOR_SETTINGS: 5,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_BURST_CAPTURE: 6,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_YUV_REPROCESSING: 7,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_DEPTH_OUTPUT: 8,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_CONSTRAINED_HIGH_SPEED_VIDEO: 9,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_MOTION_TRACKING: 10,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_LOGICAL_MULTI_CAMERA: 11,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_MONOCHROME: 12,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_SECURE_IMAGE_DATA: 13,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_SYSTEM_CAMERA: 14,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_OFFLINE_PROCESSING: 15,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_ULTRA_HIGH_RESOLUTION_SENSOR: 16,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_REMOSAIC_REPROCESSING: 17,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_DYNAMIC_RANGE_TEN_BIT: 18,
  ANDROID_REQUEST_AVAILABLE_CAPABILITIES_STREAM_USE_CASE: 19,
};
cros.mojom.AndroidRequestAvailableCapabilitiesSpec = { $: mojo.internal.Enum() };

// Enum: AndroidRequestAvailableDynamicRangeProfilesMap
cros.mojom.AndroidRequestAvailableDynamicRangeProfilesMap = {
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_STANDARD: 0,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_HLG10: 1,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_HDR10: 2,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_HDR10_PLUS: 3,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_DOLBY_VISION_10B_HDR_REF: 4,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_DOLBY_VISION_10B_HDR_REF_PO: 5,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_DOLBY_VISION_10B_HDR_OEM: 6,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_DOLBY_VISION_10B_HDR_OEM_PO: 7,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_DOLBY_VISION_8B_HDR_REF: 8,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_DOLBY_VISION_8B_HDR_REF_PO: 9,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_DOLBY_VISION_8B_HDR_OEM: 10,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_DOLBY_VISION_8B_HDR_OEM_PO: 11,
  ANDROID_REQUEST_AVAILABLE_DYNAMIC_RANGE_PROFILES_MAP_MAX: 12,
};
cros.mojom.AndroidRequestAvailableDynamicRangeProfilesMapSpec = { $: mojo.internal.Enum() };

// Enum: AndroidScalerAvailableFormats
cros.mojom.AndroidScalerAvailableFormats = {
  ANDROID_SCALER_AVAILABLE_FORMATS_RAW16: 0,
  ANDROID_SCALER_AVAILABLE_FORMATS_RAW_OPAQUE: 1,
  ANDROID_SCALER_AVAILABLE_FORMATS_YV12: 2,
  ANDROID_SCALER_AVAILABLE_FORMATS_YCrCb_420_SP: 3,
  ANDROID_SCALER_AVAILABLE_FORMATS_IMPLEMENTATION_DEFINED: 4,
  ANDROID_SCALER_AVAILABLE_FORMATS_YCbCr_420_888: 5,
  ANDROID_SCALER_AVAILABLE_FORMATS_BLOB: 6,
  ANDROID_SCALER_AVAILABLE_FORMATS_RAW10: 7,
  ANDROID_SCALER_AVAILABLE_FORMATS_RAW12: 8,
  ANDROID_SCALER_AVAILABLE_FORMATS_Y8: 9,
};
cros.mojom.AndroidScalerAvailableFormatsSpec = { $: mojo.internal.Enum() };

// Enum: AndroidScalerAvailableStreamConfigurations
cros.mojom.AndroidScalerAvailableStreamConfigurations = {
  ANDROID_SCALER_AVAILABLE_STREAM_CONFIGURATIONS_OUTPUT: 0,
  ANDROID_SCALER_AVAILABLE_STREAM_CONFIGURATIONS_INPUT: 1,
};
cros.mojom.AndroidScalerAvailableStreamConfigurationsSpec = { $: mojo.internal.Enum() };

// Enum: AndroidScalerCroppingType
cros.mojom.AndroidScalerCroppingType = {
  ANDROID_SCALER_CROPPING_TYPE_CENTER_ONLY: 0,
  ANDROID_SCALER_CROPPING_TYPE_FREEFORM: 1,
};
cros.mojom.AndroidScalerCroppingTypeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidScalerAvailableRecommendedStreamConfigurations
cros.mojom.AndroidScalerAvailableRecommendedStreamConfigurations = {
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_PREVIEW: 0,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_RECORD: 1,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_VIDEO_SNAPSHOT: 2,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_SNAPSHOT: 3,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_ZSL: 4,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_RAW: 5,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_LOW_LATENCY_SNAPSHOT: 6,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_PUBLIC_END: 7,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_10BIT_OUTPUT: 8,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_PUBLIC_END_3_8: 9,
  ANDROID_SCALER_AVAILABLE_RECOMMENDED_STREAM_CONFIGURATIONS_VENDOR_START: 10,
};
cros.mojom.AndroidScalerAvailableRecommendedStreamConfigurationsSpec = { $: mojo.internal.Enum() };

// Enum: AndroidScalerRotateAndCrop
cros.mojom.AndroidScalerRotateAndCrop = {
  ANDROID_SCALER_ROTATE_AND_CROP_NONE: 0,
  ANDROID_SCALER_ROTATE_AND_CROP_90: 1,
  ANDROID_SCALER_ROTATE_AND_CROP_180: 2,
  ANDROID_SCALER_ROTATE_AND_CROP_270: 3,
  ANDROID_SCALER_ROTATE_AND_CROP_AUTO: 4,
};
cros.mojom.AndroidScalerRotateAndCropSpec = { $: mojo.internal.Enum() };

// Enum: AndroidScalerPhysicalCameraMultiResolutionStreamConfigurations
cros.mojom.AndroidScalerPhysicalCameraMultiResolutionStreamConfigurations = {
  ANDROID_SCALER_PHYSICAL_CAMERA_MULTI_RESOLUTION_STREAM_CONFIGURATIONS_OUTPUT: 0,
  ANDROID_SCALER_PHYSICAL_CAMERA_MULTI_RESOLUTION_STREAM_CONFIGURATIONS_INPUT: 1,
};
cros.mojom.AndroidScalerPhysicalCameraMultiResolutionStreamConfigurationsSpec = { $: mojo.internal.Enum() };

// Enum: AndroidScalerAvailableStreamConfigurationsMaximumResolution
cros.mojom.AndroidScalerAvailableStreamConfigurationsMaximumResolution = {
  ANDROID_SCALER_AVAILABLE_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION_OUTPUT: 0,
  ANDROID_SCALER_AVAILABLE_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION_INPUT: 1,
};
cros.mojom.AndroidScalerAvailableStreamConfigurationsMaximumResolutionSpec = { $: mojo.internal.Enum() };

// Enum: AndroidScalerMultiResolutionStreamSupported
cros.mojom.AndroidScalerMultiResolutionStreamSupported = {
  ANDROID_SCALER_MULTI_RESOLUTION_STREAM_SUPPORTED_FALSE: 0,
  ANDROID_SCALER_MULTI_RESOLUTION_STREAM_SUPPORTED_TRUE: 1,
};
cros.mojom.AndroidScalerMultiResolutionStreamSupportedSpec = { $: mojo.internal.Enum() };

// Enum: AndroidScalerCropRegionSet
cros.mojom.AndroidScalerCropRegionSet = {
  ANDROID_SCALER_CROP_REGION_SET_FALSE: 0,
  ANDROID_SCALER_CROP_REGION_SET_TRUE: 1,
};
cros.mojom.AndroidScalerCropRegionSetSpec = { $: mojo.internal.Enum() };

// Enum: AndroidScalerAvailableStreamUseCases
cros.mojom.AndroidScalerAvailableStreamUseCases = {
  ANDROID_SCALER_AVAILABLE_STREAM_USE_CASES_DEFAULT: 0,
  ANDROID_SCALER_AVAILABLE_STREAM_USE_CASES_PREVIEW: 1,
  ANDROID_SCALER_AVAILABLE_STREAM_USE_CASES_STILL_CAPTURE: 2,
  ANDROID_SCALER_AVAILABLE_STREAM_USE_CASES_VIDEO_RECORD: 3,
  ANDROID_SCALER_AVAILABLE_STREAM_USE_CASES_PREVIEW_VIDEO_STILL: 4,
  ANDROID_SCALER_AVAILABLE_STREAM_USE_CASES_VIDEO_CALL: 5,
  ANDROID_SCALER_AVAILABLE_STREAM_USE_CASES_VENDOR_START: 6,
};
cros.mojom.AndroidScalerAvailableStreamUseCasesSpec = { $: mojo.internal.Enum() };

// Enum: AndroidSensorReferenceIlluminant1
cros.mojom.AndroidSensorReferenceIlluminant1 = {
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_DAYLIGHT: 0,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_FLUORESCENT: 1,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_TUNGSTEN: 2,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_FLASH: 3,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_FINE_WEATHER: 4,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_CLOUDY_WEATHER: 5,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_SHADE: 6,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_DAYLIGHT_FLUORESCENT: 7,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_DAY_WHITE_FLUORESCENT: 8,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_COOL_WHITE_FLUORESCENT: 9,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_WHITE_FLUORESCENT: 10,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_STANDARD_A: 11,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_STANDARD_B: 12,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_STANDARD_C: 13,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_D55: 14,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_D65: 15,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_D75: 16,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_D50: 17,
  ANDROID_SENSOR_REFERENCE_ILLUMINANT1_ISO_STUDIO_TUNGSTEN: 18,
};
cros.mojom.AndroidSensorReferenceIlluminant1Spec = { $: mojo.internal.Enum() };

// Enum: AndroidSensorTestPatternMode
cros.mojom.AndroidSensorTestPatternMode = {
  ANDROID_SENSOR_TEST_PATTERN_MODE_OFF: 0,
  ANDROID_SENSOR_TEST_PATTERN_MODE_SOLID_COLOR: 1,
  ANDROID_SENSOR_TEST_PATTERN_MODE_COLOR_BARS: 2,
  ANDROID_SENSOR_TEST_PATTERN_MODE_COLOR_BARS_FADE_TO_GRAY: 3,
  ANDROID_SENSOR_TEST_PATTERN_MODE_PN9: 4,
  ANDROID_SENSOR_TEST_PATTERN_MODE_BLACK: 5,
  ANDROID_SENSOR_TEST_PATTERN_MODE_CUSTOM1: 6,
};
cros.mojom.AndroidSensorTestPatternModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidSensorPixelMode
cros.mojom.AndroidSensorPixelMode = {
  ANDROID_SENSOR_PIXEL_MODE_DEFAULT: 0,
  ANDROID_SENSOR_PIXEL_MODE_MAXIMUM_RESOLUTION: 1,
};
cros.mojom.AndroidSensorPixelModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidSensorRawBinningFactorUsed
cros.mojom.AndroidSensorRawBinningFactorUsed = {
  ANDROID_SENSOR_RAW_BINNING_FACTOR_USED_TRUE: 0,
  ANDROID_SENSOR_RAW_BINNING_FACTOR_USED_FALSE: 1,
};
cros.mojom.AndroidSensorRawBinningFactorUsedSpec = { $: mojo.internal.Enum() };

// Enum: AndroidSensorInfoColorFilterArrangement
cros.mojom.AndroidSensorInfoColorFilterArrangement = {
  ANDROID_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_RGGB: 0,
  ANDROID_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_GRBG: 1,
  ANDROID_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_GBRG: 2,
  ANDROID_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_BGGR: 3,
  ANDROID_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_RGB: 4,
  ANDROID_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_MONO: 5,
  ANDROID_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT_NIR: 6,
};
cros.mojom.AndroidSensorInfoColorFilterArrangementSpec = { $: mojo.internal.Enum() };

// Enum: AndroidSensorInfoTimestampSource
cros.mojom.AndroidSensorInfoTimestampSource = {
  ANDROID_SENSOR_INFO_TIMESTAMP_SOURCE_UNKNOWN: 0,
  ANDROID_SENSOR_INFO_TIMESTAMP_SOURCE_REALTIME: 1,
};
cros.mojom.AndroidSensorInfoTimestampSourceSpec = { $: mojo.internal.Enum() };

// Enum: AndroidSensorInfoLensShadingApplied
cros.mojom.AndroidSensorInfoLensShadingApplied = {
  ANDROID_SENSOR_INFO_LENS_SHADING_APPLIED_FALSE: 0,
  ANDROID_SENSOR_INFO_LENS_SHADING_APPLIED_TRUE: 1,
};
cros.mojom.AndroidSensorInfoLensShadingAppliedSpec = { $: mojo.internal.Enum() };

// Enum: AndroidShadingMode
cros.mojom.AndroidShadingMode = {
  ANDROID_SHADING_MODE_OFF: 0,
  ANDROID_SHADING_MODE_FAST: 1,
  ANDROID_SHADING_MODE_HIGH_QUALITY: 2,
};
cros.mojom.AndroidShadingModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidStatisticsFaceDetectMode
cros.mojom.AndroidStatisticsFaceDetectMode = {
  ANDROID_STATISTICS_FACE_DETECT_MODE_OFF: 0,
  ANDROID_STATISTICS_FACE_DETECT_MODE_SIMPLE: 1,
  ANDROID_STATISTICS_FACE_DETECT_MODE_FULL: 2,
};
cros.mojom.AndroidStatisticsFaceDetectModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidStatisticsHistogramMode
cros.mojom.AndroidStatisticsHistogramMode = {
  ANDROID_STATISTICS_HISTOGRAM_MODE_OFF: 0,
  ANDROID_STATISTICS_HISTOGRAM_MODE_ON: 1,
};
cros.mojom.AndroidStatisticsHistogramModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidStatisticsSharpnessMapMode
cros.mojom.AndroidStatisticsSharpnessMapMode = {
  ANDROID_STATISTICS_SHARPNESS_MAP_MODE_OFF: 0,
  ANDROID_STATISTICS_SHARPNESS_MAP_MODE_ON: 1,
};
cros.mojom.AndroidStatisticsSharpnessMapModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidStatisticsHotPixelMapMode
cros.mojom.AndroidStatisticsHotPixelMapMode = {
  ANDROID_STATISTICS_HOT_PIXEL_MAP_MODE_OFF: 0,
  ANDROID_STATISTICS_HOT_PIXEL_MAP_MODE_ON: 1,
};
cros.mojom.AndroidStatisticsHotPixelMapModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidStatisticsSceneFlicker
cros.mojom.AndroidStatisticsSceneFlicker = {
  ANDROID_STATISTICS_SCENE_FLICKER_NONE: 0,
  ANDROID_STATISTICS_SCENE_FLICKER_50HZ: 1,
  ANDROID_STATISTICS_SCENE_FLICKER_60HZ: 2,
};
cros.mojom.AndroidStatisticsSceneFlickerSpec = { $: mojo.internal.Enum() };

// Enum: AndroidStatisticsLensShadingMapMode
cros.mojom.AndroidStatisticsLensShadingMapMode = {
  ANDROID_STATISTICS_LENS_SHADING_MAP_MODE_OFF: 0,
  ANDROID_STATISTICS_LENS_SHADING_MAP_MODE_ON: 1,
};
cros.mojom.AndroidStatisticsLensShadingMapModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidStatisticsOisDataMode
cros.mojom.AndroidStatisticsOisDataMode = {
  ANDROID_STATISTICS_OIS_DATA_MODE_OFF: 0,
  ANDROID_STATISTICS_OIS_DATA_MODE_ON: 1,
};
cros.mojom.AndroidStatisticsOisDataModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidTonemapMode
cros.mojom.AndroidTonemapMode = {
  ANDROID_TONEMAP_MODE_CONTRAST_CURVE: 0,
  ANDROID_TONEMAP_MODE_FAST: 1,
  ANDROID_TONEMAP_MODE_HIGH_QUALITY: 2,
  ANDROID_TONEMAP_MODE_GAMMA_VALUE: 3,
  ANDROID_TONEMAP_MODE_PRESET_CURVE: 4,
};
cros.mojom.AndroidTonemapModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidTonemapPresetCurve
cros.mojom.AndroidTonemapPresetCurve = {
  ANDROID_TONEMAP_PRESET_CURVE_SRGB: 0,
  ANDROID_TONEMAP_PRESET_CURVE_REC709: 1,
};
cros.mojom.AndroidTonemapPresetCurveSpec = { $: mojo.internal.Enum() };

// Enum: AndroidLedTransmit
cros.mojom.AndroidLedTransmit = {
  ANDROID_LED_TRANSMIT_OFF: 0,
  ANDROID_LED_TRANSMIT_ON: 1,
};
cros.mojom.AndroidLedTransmitSpec = { $: mojo.internal.Enum() };

// Enum: AndroidLedAvailableLeds
cros.mojom.AndroidLedAvailableLeds = {
  ANDROID_LED_AVAILABLE_LEDS_TRANSMIT: 0,
};
cros.mojom.AndroidLedAvailableLedsSpec = { $: mojo.internal.Enum() };

// Enum: AndroidInfoSupportedHardwareLevel
cros.mojom.AndroidInfoSupportedHardwareLevel = {
  ANDROID_INFO_SUPPORTED_HARDWARE_LEVEL_LIMITED: 0,
  ANDROID_INFO_SUPPORTED_HARDWARE_LEVEL_FULL: 1,
  ANDROID_INFO_SUPPORTED_HARDWARE_LEVEL_LEGACY: 2,
  ANDROID_INFO_SUPPORTED_HARDWARE_LEVEL_3: 3,
  ANDROID_INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL: 4,
};
cros.mojom.AndroidInfoSupportedHardwareLevelSpec = { $: mojo.internal.Enum() };

// Enum: AndroidInfoSupportedBufferManagementVersion
cros.mojom.AndroidInfoSupportedBufferManagementVersion = {
  ANDROID_INFO_SUPPORTED_BUFFER_MANAGEMENT_VERSION_HIDL_DEVICE_3_5: 0,
};
cros.mojom.AndroidInfoSupportedBufferManagementVersionSpec = { $: mojo.internal.Enum() };

// Enum: AndroidBlackLevelLock
cros.mojom.AndroidBlackLevelLock = {
  ANDROID_BLACK_LEVEL_LOCK_OFF: 0,
  ANDROID_BLACK_LEVEL_LOCK_ON: 1,
};
cros.mojom.AndroidBlackLevelLockSpec = { $: mojo.internal.Enum() };

// Enum: AndroidSyncFrameNumber
cros.mojom.AndroidSyncFrameNumber = {
  ANDROID_SYNC_FRAME_NUMBER_CONVERGING: 0,
  ANDROID_SYNC_FRAME_NUMBER_UNKNOWN: 1,
};
cros.mojom.AndroidSyncFrameNumberSpec = { $: mojo.internal.Enum() };

// Enum: AndroidSyncMaxLatency
cros.mojom.AndroidSyncMaxLatency = {
  ANDROID_SYNC_MAX_LATENCY_PER_FRAME_CONTROL: 0,
  ANDROID_SYNC_MAX_LATENCY_UNKNOWN: 1,
};
cros.mojom.AndroidSyncMaxLatencySpec = { $: mojo.internal.Enum() };

// Enum: AndroidDepthAvailableDepthStreamConfigurations
cros.mojom.AndroidDepthAvailableDepthStreamConfigurations = {
  ANDROID_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS_OUTPUT: 0,
  ANDROID_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS_INPUT: 1,
};
cros.mojom.AndroidDepthAvailableDepthStreamConfigurationsSpec = { $: mojo.internal.Enum() };

// Enum: AndroidDepthDepthIsExclusive
cros.mojom.AndroidDepthDepthIsExclusive = {
  ANDROID_DEPTH_DEPTH_IS_EXCLUSIVE_FALSE: 0,
  ANDROID_DEPTH_DEPTH_IS_EXCLUSIVE_TRUE: 1,
};
cros.mojom.AndroidDepthDepthIsExclusiveSpec = { $: mojo.internal.Enum() };

// Enum: AndroidDepthAvailableDynamicDepthStreamConfigurations
cros.mojom.AndroidDepthAvailableDynamicDepthStreamConfigurations = {
  ANDROID_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STREAM_CONFIGURATIONS_OUTPUT: 0,
  ANDROID_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STREAM_CONFIGURATIONS_INPUT: 1,
};
cros.mojom.AndroidDepthAvailableDynamicDepthStreamConfigurationsSpec = { $: mojo.internal.Enum() };

// Enum: AndroidDepthAvailableDepthStreamConfigurationsMaximumResolution
cros.mojom.AndroidDepthAvailableDepthStreamConfigurationsMaximumResolution = {
  ANDROID_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION_OUTPUT: 0,
  ANDROID_DEPTH_AVAILABLE_DEPTH_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION_INPUT: 1,
};
cros.mojom.AndroidDepthAvailableDepthStreamConfigurationsMaximumResolutionSpec = { $: mojo.internal.Enum() };

// Enum: AndroidDepthAvailableDynamicDepthStreamConfigurationsMaximumResolution
cros.mojom.AndroidDepthAvailableDynamicDepthStreamConfigurationsMaximumResolution = {
  ANDROID_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION_OUTPUT: 0,
  ANDROID_DEPTH_AVAILABLE_DYNAMIC_DEPTH_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION_INPUT: 1,
};
cros.mojom.AndroidDepthAvailableDynamicDepthStreamConfigurationsMaximumResolutionSpec = { $: mojo.internal.Enum() };

// Enum: AndroidLogicalMultiCameraSensorSyncType
cros.mojom.AndroidLogicalMultiCameraSensorSyncType = {
  ANDROID_LOGICAL_MULTI_CAMERA_SENSOR_SYNC_TYPE_APPROXIMATE: 0,
  ANDROID_LOGICAL_MULTI_CAMERA_SENSOR_SYNC_TYPE_CALIBRATED: 1,
};
cros.mojom.AndroidLogicalMultiCameraSensorSyncTypeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidDistortionCorrectionMode
cros.mojom.AndroidDistortionCorrectionMode = {
  ANDROID_DISTORTION_CORRECTION_MODE_OFF: 0,
  ANDROID_DISTORTION_CORRECTION_MODE_FAST: 1,
  ANDROID_DISTORTION_CORRECTION_MODE_HIGH_QUALITY: 2,
};
cros.mojom.AndroidDistortionCorrectionModeSpec = { $: mojo.internal.Enum() };

// Enum: AndroidHeicAvailableHeicStreamConfigurations
cros.mojom.AndroidHeicAvailableHeicStreamConfigurations = {
  ANDROID_HEIC_AVAILABLE_HEIC_STREAM_CONFIGURATIONS_OUTPUT: 0,
  ANDROID_HEIC_AVAILABLE_HEIC_STREAM_CONFIGURATIONS_INPUT: 1,
};
cros.mojom.AndroidHeicAvailableHeicStreamConfigurationsSpec = { $: mojo.internal.Enum() };

// Enum: AndroidHeicAvailableHeicStreamConfigurationsMaximumResolution
cros.mojom.AndroidHeicAvailableHeicStreamConfigurationsMaximumResolution = {
  ANDROID_HEIC_AVAILABLE_HEIC_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION_OUTPUT: 0,
  ANDROID_HEIC_AVAILABLE_HEIC_STREAM_CONFIGURATIONS_MAXIMUM_RESOLUTION_INPUT: 1,
};
cros.mojom.AndroidHeicAvailableHeicStreamConfigurationsMaximumResolutionSpec = { $: mojo.internal.Enum() };

// Enum: AndroidHeicInfoSupported
cros.mojom.AndroidHeicInfoSupported = {
  ANDROID_HEIC_INFO_SUPPORTED_FALSE: 0,
  ANDROID_HEIC_INFO_SUPPORTED_TRUE: 1,
};
cros.mojom.AndroidHeicInfoSupportedSpec = { $: mojo.internal.Enum() };

// Enum: AndroidAutomotiveLocation
cros.mojom.AndroidAutomotiveLocation = {
  ANDROID_AUTOMOTIVE_LOCATION_INTERIOR: 0,
  ANDROID_AUTOMOTIVE_LOCATION_EXTERIOR_OTHER: 1,
  ANDROID_AUTOMOTIVE_LOCATION_EXTERIOR_FRONT: 2,
  ANDROID_AUTOMOTIVE_LOCATION_EXTERIOR_REAR: 3,
  ANDROID_AUTOMOTIVE_LOCATION_EXTERIOR_LEFT: 4,
  ANDROID_AUTOMOTIVE_LOCATION_EXTERIOR_RIGHT: 5,
  ANDROID_AUTOMOTIVE_LOCATION_EXTRA_OTHER: 6,
  ANDROID_AUTOMOTIVE_LOCATION_EXTRA_FRONT: 7,
  ANDROID_AUTOMOTIVE_LOCATION_EXTRA_REAR: 8,
  ANDROID_AUTOMOTIVE_LOCATION_EXTRA_LEFT: 9,
  ANDROID_AUTOMOTIVE_LOCATION_EXTRA_RIGHT: 10,
};
cros.mojom.AndroidAutomotiveLocationSpec = { $: mojo.internal.Enum() };

// Enum: AndroidAutomotiveLensFacing
cros.mojom.AndroidAutomotiveLensFacing = {
  ANDROID_AUTOMOTIVE_LENS_FACING_EXTERIOR_OTHER: 0,
  ANDROID_AUTOMOTIVE_LENS_FACING_EXTERIOR_FRONT: 1,
  ANDROID_AUTOMOTIVE_LENS_FACING_EXTERIOR_REAR: 2,
  ANDROID_AUTOMOTIVE_LENS_FACING_EXTERIOR_LEFT: 3,
  ANDROID_AUTOMOTIVE_LENS_FACING_EXTERIOR_RIGHT: 4,
  ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_OTHER: 5,
  ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_1_LEFT: 6,
  ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_1_CENTER: 7,
  ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_1_RIGHT: 8,
  ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_2_LEFT: 9,
  ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_2_CENTER: 10,
  ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_2_RIGHT: 11,
  ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_3_LEFT: 12,
  ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_3_CENTER: 13,
  ANDROID_AUTOMOTIVE_LENS_FACING_INTERIOR_SEAT_ROW_3_RIGHT: 14,
};
cros.mojom.AndroidAutomotiveLensFacingSpec = { $: mojo.internal.Enum() };
