// Auto-generated MojoJS binding
// Source: chromium_src/services/network/public/mojom/permissions_policy/permissions_policy_feature.mojom
// Module: network.mojom

'use strict';

// Module namespace
var network = network || {};
network.mojom = network.mojom || {};


// Enum: PermissionsPolicyFeature
network.mojom.PermissionsPolicyFeature = {
  kNotFound: 0,
  kAutoplay: 1,
  kCamera: 2,
  kEncryptedMedia: 3,
  kFullscreen: 4,
  kGeolocation: 5,
  kMicrophone: 6,
  kMidiFeature: 7,
  kPayment: 8,
  kSyncXHR: 9,
  kUsb: 10,
  kAccelerometer: 11,
  kAmbientLightSensor: 12,
  kGyroscope: 13,
  kMagnetometer: 14,
  kPictureInPicture: 15,
  kVerticalScroll: 16,
  kScreenWakeLock: 17,
  kFrobulate: 18,
  kSerial: 19,
  kHid: 20,
  kIdleDetection: 21,
  kExecutionWhileOutOfViewport: 22,
  kExecutionWhileNotRendered: 23,
  kFocusWithoutUserActivation: 24,
  kClientHintDPR: 25,
  kClientHintDeviceMemory: 26,
  kClientHintDownlink: 27,
  kClientHintECT: 28,
  kClientHintRTT: 29,
  kClientHintUA: 30,
  kClientHintUAArch: 31,
  kClientHintUAModel: 32,
  kClientHintUAPlatform: 33,
  kClientHintViewportWidth: 34,
  kClientHintWidth: 35,
  kWebXr: 36,
  kPublicKeyCredentialsGet: 37,
  kClientHintUAMobile: 38,
  kStorageAccessAPI: 39,
  kClientHintUAFullVersion: 40,
  kTrustTokenRedemption: 41,
  kAttributionReporting: 42,
  kClientHintUAPlatformVersion: 43,
  kCrossOriginIsolated: 44,
  kClipboardRead: 45,
  kClipboardWrite: 46,
  kWebShare: 47,
  kGamepad: 48,
  kOTPCredentials: 49,
  kDisplayCapture: 50,
  kAutofill: 51,
  kDirectSockets: 52,
  kClientHintPrefersColorScheme: 53,
  kWindowManagement: 54,
  kClientHintUABitness: 55,
  kClientHintViewportHeight: 56,
  kKeyboardMap: 57,
  kRunAdAuction: 58,
  kJoinAdInterestGroup: 59,
  kClientHintUAFullVersionList: 60,
  kClientHintUAWoW64: 61,
  kBrowsingTopics: 62,
  kBrowsingTopicsBackwardCompatible: 63,
  kClientHintSaveData: 64,
  kLocalFonts: 65,
  kBluetooth: 66,
  kIdentityCredentialsGet: 67,
  kSharedStorage: 68,
  kUnload: 69,
  kClientHintPrefersReducedMotion: 70,
  kComputePressure: 71,
  kSmartCard: 72,
  kSharedStorageSelectUrl: 73,
  kPrivateAggregation: 74,
  kPrivateStateTokenIssuance: 75,
  kClientHintUAFormFactors: 76,
  kClientHintPrefersReducedTransparency: 77,
  kWebPrinting: 78,
  kUsbUnrestricted: 79,
  kCapturedSurfaceControl: 80,
  kSubApps: 81,
  kPublicKeyCredentialsCreate: 82,
  kSpeakerSelection: 83,
  kDeferredFetch: 84,
  kDigitalCredentialsGet: 85,
  kMediaPlaybackWhileNotVisible: 86,
  kAllScreensCapture: 87,
  kWebAppInstallation: 88,
  kControlledFrame: 89,
  kDirectSocketsPrivate: 90,
  kFencedUnpartitionedStorageRead: 91,
  kDeferredFetchMinimal: 92,
  kClientHintUAHighEntropyValues: 93,
  kSummarizer: 94,
  kWriter: 95,
  kRewriter: 96,
  kTranslator: 97,
  kLanguageDetector: 98,
  kDeviceAttributes: 99,
  kLocalNetworkAccess: 100,
  kRecordAdAuctionEvents: 101,
  kOnDeviceSpeechRecognition: 102,
  kLanguageModel: 103,
  kAriaNotify: 104,
  kDigitalCredentialsCreate: 105,
  kMulticastInDirectSockets: 106,
  kManualText: 107,
  kLocalNetwork: 108,
  kLoopbackNetwork: 109,
};
network.mojom.PermissionsPolicyFeatureSpec = { $: mojo.internal.Enum() };
