// Auto-generated MojoJS binding
// Source: chromium_src/services/network/public/mojom/permissions_policy/permissions_policy_feature.mojom
// Module: network.mojom

'use strict';

// Module namespace
var network = network || {};
network.mojom = network.mojom || {};

network.mojom.PermissionsPolicyFeatureSpec = { $: mojo.internal.Enum() };

// Enum: PermissionsPolicyFeature
network.mojom.PermissionsPolicyFeature = {
  kNotFound: 0,
  kAutoplay: 1,
  kCamera: 2,
  kEncryptedMedia: 3,
  kFullscreen: 4,
  kGeolocation: 5,
  kMicrophone: 6,
  kMidiFeature: 7,
  kPayment: 8,
  kSyncXHR: 13,
  kUsb: 14,
  kAccelerometer: 17,
  kAmbientLightSensor: 18,
  kGyroscope: 19,
  kMagnetometer: 20,
  kPictureInPicture: 26,
  kVerticalScroll: 27,
  kScreenWakeLock: 31,
  kFrobulate: 41,
  kSerial: 42,
  kHid: 43,
  kIdleDetection: 44,
  kExecutionWhileOutOfViewport: 50,
  kExecutionWhileNotRendered: 51,
  kFocusWithoutUserActivation: 52,
  kClientHintDPR: 53,
  kClientHintDeviceMemory: 54,
  kClientHintDownlink: 55,
  kClientHintECT: 56,
  kClientHintRTT: 58,
  kClientHintUA: 59,
  kClientHintUAArch: 60,
  kClientHintUAModel: 61,
  kClientHintUAPlatform: 62,
  kClientHintViewportWidth: 63,
  kClientHintWidth: 64,
  kWebXr: 66,
  kPublicKeyCredentialsGet: 67,
  kClientHintUAMobile: 69,
  kStorageAccessAPI: 70,
  kClientHintUAFullVersion: 71,
  kTrustTokenRedemption: 72,
  kAttributionReporting: 73,
  kClientHintUAPlatformVersion: 74,
  kCrossOriginIsolated: 75,
  kClipboardRead: 76,
  kClipboardWrite: 77,
  kWebShare: 78,
  kGamepad: 79,
  kOTPCredentials: 80,
  kDisplayCapture: 81,
  kAutofill: 83,
  kDirectSockets: 84,
  kClientHintPrefersColorScheme: 85,
  kWindowManagement: 86,
  kClientHintUABitness: 87,
  kClientHintViewportHeight: 89,
  kKeyboardMap: 90,
  kRunAdAuction: 91,
  kJoinAdInterestGroup: 92,
  kClientHintUAFullVersionList: 93,
  kClientHintUAWoW64: 95,
  kBrowsingTopics: 97,
  kBrowsingTopicsBackwardCompatible: 98,
  kClientHintSaveData: 99,
  kLocalFonts: 100,
  kBluetooth: 101,
  kIdentityCredentialsGet: 102,
  kSharedStorage: 103,
  kUnload: 104,
  kClientHintPrefersReducedMotion: 105,
  kComputePressure: 106,
  kSmartCard: 107,
  kSharedStorageSelectUrl: 108,
  kPrivateAggregation: 109,
  kPrivateStateTokenIssuance: 110,
  kClientHintUAFormFactors: 111,
  kClientHintPrefersReducedTransparency: 112,
  kWebPrinting: 113,
  kUsbUnrestricted: 114,
  kCapturedSurfaceControl: 115,
  kSubApps: 116,
  kPublicKeyCredentialsCreate: 117,
  kSpeakerSelection: 118,
  kDeferredFetch: 119,
  kDigitalCredentialsGet: 120,
  kMediaPlaybackWhileNotVisible: 121,
  kAllScreensCapture: 122,
  kWebAppInstallation: 124,
  kControlledFrame: 125,
  kDirectSocketsPrivate: 126,
  kFencedUnpartitionedStorageRead: 127,
  kDeferredFetchMinimal: 128,
  kClientHintUAHighEntropyValues: 129,
  kSummarizer: 130,
  kWriter: 131,
  kRewriter: 132,
  kTranslator: 133,
  kLanguageDetector: 134,
  kDeviceAttributes: 135,
  kLocalNetworkAccess: 136,
  kRecordAdAuctionEvents: 137,
  kOnDeviceSpeechRecognition: 138,
  kLanguageModel: 139,
  kAriaNotify: 140,
  kDigitalCredentialsCreate: 141,
  kMulticastInDirectSockets: 142,
  kManualText: 143,
  kLocalNetwork: 144,
  kLoopbackNetwork: 145,
};
