// Auto-generated MojoJS binding
// Source: chromium_src/ui/color/color_id.mojom
// Module: color.mojom

'use strict';

// Module namespace
var color = color || {};
color.mojom = color.mojom || {};


// Enum: RendererColorId
color.mojom.RendererColorId = {
  kColorCssSystemActiveText: 0,
  kColorCssSystemBtnFace: 1,
  kColorCssSystemBtnText: 2,
  kColorCssSystemField: 3,
  kColorCssSystemFieldText: 4,
  kColorCssSystemGrayText: 5,
  kColorCssSystemHighlight: 6,
  kColorCssSystemHighlightText: 7,
  kColorCssSystemHotlight: 8,
  kColorCssSystemLinkText: 9,
  kColorCssSystemMenuHilight: 10,
  kColorCssSystemScrollbar: 11,
  kColorCssSystemVisitedText: 12,
  kColorCssSystemWindow: 13,
  kColorCssSystemWindowText: 14,
  kColorMenuBackground: 15,
  kColorMenuItemBackgroundSelected: 16,
  kColorMenuSeparator: 17,
  kColorOverlayScrollbarFill: 18,
  kColorOverlayScrollbarFillHovered: 19,
  kColorOverlayScrollbarStroke: 20,
  kColorOverlayScrollbarStrokeHovered: 21,
  kColorWebNativeControlAccent: 22,
  kColorWebNativeControlAccentDisabled: 23,
  kColorWebNativeControlAccentHovered: 24,
  kColorWebNativeControlAccentPressed: 25,
  kColorWebNativeControlAutoCompleteBackground: 26,
  kColorWebNativeControlBorder: 27,
  kColorWebNativeControlBorderDisabled: 28,
  kColorWebNativeControlBorderHovered: 29,
  kColorWebNativeControlBorderPressed: 30,
  kColorWebNativeControlButtonBorder: 31,
  kColorWebNativeControlButtonBorderDisabled: 32,
  kColorWebNativeControlButtonBorderHovered: 33,
  kColorWebNativeControlButtonBorderPressed: 34,
  kColorWebNativeControlButtonFill: 35,
  kColorWebNativeControlButtonFillDisabled: 36,
  kColorWebNativeControlButtonFillHovered: 37,
  kColorWebNativeControlButtonFillPressed: 38,
  kColorWebNativeControlCheckboxBackground: 39,
  kColorWebNativeControlCheckboxBackgroundDisabled: 40,
  kColorWebNativeControlFill: 41,
  kColorWebNativeControlFillDisabled: 42,
  kColorWebNativeControlFillHovered: 43,
  kColorWebNativeControlFillPressed: 44,
  kColorWebNativeControlLightenLayer: 45,
  kColorWebNativeControlProgressValue: 46,
  kColorWebNativeControlScrollbarArrowBackgroundDisabled: 47,
  kColorWebNativeControlScrollbarArrowBackgroundHovered: 48,
  kColorWebNativeControlScrollbarArrowBackgroundPressed: 49,
  kColorWebNativeControlScrollbarArrowForeground: 50,
  kColorWebNativeControlScrollbarArrowForegroundDisabled: 51,
  kColorWebNativeControlScrollbarArrowForegroundPressed: 52,
  kColorWebNativeControlScrollbarCorner: 53,
  kColorWebNativeControlScrollbarThumb: 54,
  kColorWebNativeControlScrollbarThumbHovered: 55,
  kColorWebNativeControlScrollbarThumbOverlayMinimalMode: 56,
  kColorWebNativeControlScrollbarThumbPressed: 57,
  kColorWebNativeControlScrollbarTrack: 58,
  kColorWebNativeControlSlider: 59,
  kColorWebNativeControlSliderBorder: 60,
  kColorWebNativeControlSliderBorderHovered: 61,
  kColorWebNativeControlSliderBorderPressed: 62,
  kColorWebNativeControlSliderDisabled: 63,
  kColorWebNativeControlSliderHovered: 64,
  kColorWebNativeControlSliderPressed: 65,
};
color.mojom.RendererColorIdSpec = { $: mojo.internal.Enum() };
